### ISSUE TITLE
Empty response

### ISSUE THREAD

**Issue by ackvf** [Eloise1988/CRYPTOBALANCE#10]
Hello, I get empty response for certain cryptocurrencies

function: `CRYPTODEXPRICE`

http://api.charmantadvisory.com/DEXPRICE2/million/usdc/UNI/{KEYID}

response: `[{}]`

I also tried it with the contract `0x6b4c7a5e3f0b99fcd83e9c089bddd6c7fce5c611`, but the result is the same.
http://api.charmantadvisory.com/DEXPRICE2/0x6b4c7a5e3f0b99fcd83e9c089bddd6c7fce5c611/usdc/UNI/{KEYID}

The pools are on Uniswap V3 and V2 too
V3 https://info.uniswap.org/#/tokens/0x6b4c7a5e3f0b99fcd83e9c089bddd6c7fce5c611
V2 https://v2.info.uniswap.org/token/0x6b4c7a5e3f0b99fcd83e9c089bddd6c7fce5c611

**Comment by Eloise1988** [comment]
Hi ackvf,

Sorry for the late response. 
I added the pair [0x6b4c7a5e3f0b99fcd83e9c089bddd6c7fce5c611 & USDC]

![image](https://user-images.githubusercontent.com/53000607/133922319-d50e121d-a3a7-469c-9058-3115eec4e471.png)
=CRYPTODEXPRICE("0X6B4C7A5E3F0B99FCD83E9C089BDDD6C7FCE5C611","USDC","UNI")

Hope that helps!
