### ISSUE TITLE
Eth2 cryptostaking

### ISSUE THREAD

**Issue by totoCZ** [Eloise1988/CRYPTOBALANCE#11]
Can you add eth2 support to see validator balances?

**Comment by Eloise1988** [comment]
Hi Tom,
You can request your total balance as a validator as follows:
I took this validator public address as an example:
=cryptostaking("ETH","0xa20ddc081b6b4b276253de5411e0a6d368b77d9246bf54ee074f97ee32354b0592271d6544ab8ef8077ed7d0c1f3e3bb")
If your are just looking for the rewards:
=cryptorewards("ETH","0xa20ddc081b6b4b276253de5411e0a6d368b77d9246bf54ee074f97ee32354b0592271d6544ab8ef8077ed7d0c1f3e3bb")
![image](https://user-images.githubusercontent.com/53000607/132224763-50ba410a-36b1-4657-b9e7-3e956a2ad44f.png)

Let me know if that's what you are looking for.

Here is the template sheet , Tab STAKING - REWARDS - ETH2
https://docs.google.com/spreadsheets/d/19aZM9IVdexcvb5U4gnC4TKOotgtkgxcEjGzMGv6OxyU/edit?usp=sharing

**Comment by totoCZ** [comment]
Thanks! I guess I made a typo when trying it.
Works perfect
