### ISSUE TITLE
Limit Authorization Scope to Current Document

### ISSUE THREAD

**Issue by ctdh** [Eloise1988/CRYPTOBALANCE#13]
The scope on these scripts exposes the users' entire google account to the script which is unnecessarily wide.
Suggest using this comment in all googlesheets scripts to limit the script scope to the current document only:

```
/*
* @OnlyCurrentDoc
*/
```

https://developers.google.com/apps-script/guides/services/authorization

**Comment by Eloise1988** [comment]
Done 
Thank you
