### ISSUE TITLE
[Feature] Add Gnosis Chain + Native token

### ISSUE THREAD

**Issue by Sigri44** [Eloise1988/CRYPTOBALANCE#16]
Hello,

Idea for next feature : 
- Add GnosisChain (old xDaiChain)
- Manage native token to CryptoBalance like (MATIC, FTM, AVAX, XDAI, BNB) who haven't contract value

Thank you for job.

**Comment by Eloise1988** [comment]
Hello,

Added: 

- GnosisChain  =CRYPTOBALANCE("gnosis"+ "GNOSIS contract address", "holder address")

- You can directly call native tokens on CryptoBalance like (MATIC, FTM, AVAX, XDAI, BNB) who haven't contract value

Regards

**Comment by daodevinc** [comment]
Hello,

For the moment USDC & USDT don't work with "gnosis" concat : 
![image](https://user-images.githubusercontent.com/9304947/153915573-97c1d83c-aaa4-4847-93f2-e41f617441c3.png)
USDC : 0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83
USDT : 0x4ECaBa5870353805a9F068101A40E0f32ed605C6

Example : 

=CRYPTOBALANCE(CONCAT("gnosis";"0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83");"0x.......")

**Comment by Eloise1988** [comment]
Hello,

It works on my side.
![image](https://user-images.githubusercontent.com/53000607/153919167-f48b14f5-9f83-4b0a-8bfb-d130e520a44b.png)
Example:
=CRYPTOBALANCE("GNOSIS0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83","0x5d9593586b4B5edBd23E7Eba8d88FD8F09D83EBd")

**Comment by daodevinc** [comment]
And with lower case ?

**Comment by Eloise1988** [comment]
It's not case sensitive, lower case will work too.

**Comment by daodevinc** [comment]
Fixed with another address, but with main, don't work. Think it's my mistake, ok for me, thank you !
