### ISSUE TITLE
CRYPTOPRICE is not working

### ISSUE THREAD

**Issue by ranmeus** [Eloise1988/CRYPTOBALANCE#19]
CRYPTOPRICE("BNB") returns empty string

**Comment by Eloise1988** [comment]
Hi,

Sorry about that. Had some issues. Should be back up now.

**Comment by Eloise1988** [comment]
The cryptoprice API is encountering issues.
In the meantime, you can use the [coingecko.gs](https://raw.githubusercontent.com/Eloise1988/COINGECKO/master/CoinGeckoV2.gs) script .
Formula is:
=geckoprice("bnb")

**Comment by ranmeus** [comment]
Perfect, thanks a bunch!
