### ISSUE TITLE
Unknown function: 'CRYPTOPRICE'.

### ISSUE THREAD

**Issue by yanrs17** [Eloise1988/CRYPTOBALANCE#3]
It is introduced in the readme but I cannot use it. Is it already removed in the code?

**Comment by Eloise1988** [comment]
Unfortunately, CryptoPrice is not an available function anymore. I created another one that gets crypto prices using the CoinGecko API.

Please refer to the following code :
https://github.com/Eloise1988/COINGECKO
https://raw.githubusercontent.com/Eloise1988/COINGECKO/master/CoinGecko.gs


Medium for more documentation:
https://medium.com/the-cryptocurious/coingecko-prices-volumes-market-caps-in-google-sheets-and-excel-a1a3ee201cb8
