### ISSUE TITLE
Crypto.org support?

### ISSUE THREAD

**Issue by UnluckyForSome** [Eloise1988/CRYPTOBALANCE#5]
Hi there, really great project this. The Crypto.org MainNet recently was launched. Is it possible to get support for this?

**Comment by Eloise1988** [comment]
Hi,

If you are looking to retrieve the amounts of CRO on the following ERC20 contract:
[https://etherscan.io/token/0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b](https://etherscan.io/token/0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b)

You need to specify the contract address in place of the ticker. For the CRO use case, it would look like:

 =CRYPTOBALANCE("0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b","Holder' address")
 
 Here is the current ticker list with all available ERC20, if you want other coins you just need to request directly using the contract address as showed above:
[https://raw.githubusercontent.com/Eloise1988/CRYPTOBALANCE/master/ALL_ERC20_BEP20.md](https://raw.githubusercontent.com/Eloise1988/CRYPTOBALANCE/master/ALL_ERC20_BEP20.md)

**Comment by UnluckyForSome** [comment]
Hi, Thanks for your reply!

I think the problem is I don’t think Crypto MainNet is on the ERC20?

For example to try and pull data from this example wallet

https://crypto.org/explorer/account/cro18wn50vxeyxcfaj5wvc73h5eg3yqjk99wcspp0e

=CRYPTOBALANCE("0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b","Holder' cro18wn50vxeyxcfaj5wvc73h5eg3yqjk99wcspp0e ")

…has no effect

Kind regards,

**Comment by UnluckyForSome** [comment]
I'm not sure the new MainNet CRO is on the ERC20?

For example if I wanted this random wallet:
https://crypto.org/explorer/account/cro1794vm2fxfstp0k88z6y7l7x6slat49el3xlddf

=CRYPTOBALANCE("0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b","ro1794vm2fxfstp0k88z6y7l7x6slat49el3xlddf")

... gives "WrongAddress"

**Comment by Eloise1988** [comment]
I've added MainNet CRO
=CRYPTOBALANCE("CRO","cro1794vm2fxfstp0k88z6y7l7x6slat49el3xlddf")
<img width="530" alt="Screen Shot 2021-04-07 at 11 32 10" src="https://user-images.githubusercontent.com/53000607/113844621-f6699280-9794-11eb-9d82-64c749bf9728.png">
