### ISSUE TITLE
Polygon's MATIC network

### ISSUE THREAD

**Issue by m3knight** [Eloise1988/CRYPTOBALANCE#6]
1st, thanks so much for your work.  It's been invaluable.

Trying to get it to pull balances off the MATIC network but can't figure it out.

**Comment by Eloise1988** [comment]
I'll add it. 
From what I see https://coinmarketcap.com/currencies/polygon/, it's an ERC20.

You can request the balance using it's contract address in place of ticker. Here's how it would work
=CRYPTOBALANCE("0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0","holder's address")
<img width="1313" alt="Screen Shot 2021-05-18 at 17 47 59" src="https://user-images.githubusercontent.com/53000607/118682957-39417000-b801-11eb-83f3-04e1b7c106db.png">
<img width="1003" alt="Screen Shot 2021-05-18 at 17 47 45" src="https://user-images.githubusercontent.com/53000607/118682963-3b0b3380-b801-11eb-89a3-2742da42a950.png">

**Comment by m3knight** [comment]
While it is an ERC20 on the ethereum mainnet, it's also also it's own L2 chain.  Since you are able to pull BNB smart chain I figured this would be doable as well?

For instance, using the wallet address 0x7988cf76751664eF4506E55e7c53184FdB37662B

Ethereum mainnet shows nothing
https://etherscan.io/address/0x7988cf76751664eF4506E55e7c53184FdB37662B

But on Matic network there's a small balance
https://explorer-mainnet.maticvigil.com/address/0x7988cf76751664eF4506E55e7c53184FdB37662B/transactions

**Comment by Eloise1988** [comment]
@m3knight 
You can now retrieve the amount
=CRYPTOBALANCE("MATIC","Holder's address")

Let me know if you are still having issues
