### ISSUE TITLE
CARDANO ADA support in CRYPTOSTAKING function

### ISSUE THREAD

**Issue by boemekeld** [Eloise1988/CRYPTOBALANCE#8]
Hi, can you support ADA in CRYPTOSTAKING function? thanks.

**Comment by Eloise1988** [comment]
Hi,

I added the ADA pair to Cryptostaking and Cryptorewards
Let me know if you still encounter problems.

Regards,
<img width="759" alt="Screen Shot 2021-06-03 at 14 59 06" src="https://user-images.githubusercontent.com/53000607/120648770-4d7da200-c47c-11eb-829e-15bb9fe36f5d.png">

**Comment by boemekeld** [comment]
@Eloise1988 yes it works perfectly! thank you so much!
