### ISSUE TITLE
Osmosis DEX

### ISSUE THREAD

**Issue by liamsi** [Eloise1988/CRYPTOBALANCE#9]
Might be a bit early (just launched last week) but would be cool if this was also supported:
https://app.osmosis.zone/
https://osmosis.imperator.co/

**Comment by Eloise1988** [comment]
![image](https://user-images.githubusercontent.com/53000607/123985047-6fa80880-d9c5-11eb-8808-a077d1cb23bb.png)
Added OSMOSIS Prices to the cryptotools dex function

**Comment by liamsi** [comment]
Neat! Thanks. Would also be cool to add Osmosis support to the `CRYPTOBALANCE` function. Closing this issue as it seems resolved for now.
